### ISSUE TITLE
Cell type and marker (Friday!)

### ISSUE THREAD

**Issue by venhoffl98** [Eugene3dotdev/CN-2023-pr-MDD-snRNA-seq#1]
Wich cell type do we want to focus on? -> find in paper
Which marker do we need for the cell type?

**Comment by AnjaRejc** [comment]
Cell type of focus for comparing female to male MDD patients is microglia and inhibitory neurons, particularly parvalbumin (PV) interneurons (because microglia and parvalbumin interneurons contributed the most DEGs in females, while deep layer excitatory neurons, astrocytes, and oligodendrocyte precursors were the major contributors in males. (Nagy et al. 2023, p. 1)).

Marker for the cell type: the marker gene for PV interneurons is PVALB (Ibid, p. 4)

Definition of a marker:
-	basically a specific gene or protein that is expressed in a particular cell type or is associated with the cell’s function. Markers in research are used to identify and isolate specific cell populations and look into their role in various e.g. diseases.

*following definitions are mostly directly copy pasted from the papers, just so you don’t have to look through the entire paper for the relevant part of info 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3410725/ 
-	“marker genes” are associated with the defined cell types 
-	the anatomical distribution of marker genes provides further evidence that they are expressed in distinct cell type

Wikipedia: https://en.wikipedia.org/wiki/Neuronal_lineage_marker: 

-	Cell markers are valuable tools for examining the function of cells in normal conditions as well as during disease
-	To localize mRNA in brain tissue, one can use a fragment of DNA or RNA as a neuronal lineage marker, a hybridization probe that detects the presence of nucleotide sequences that are complementary to the sequence in the probe (in situ hybridization). Its application have been carried out in all different tissues, but particularly useful in neuroscience. Using this technique, it is possible to locate gene expression to specific cell types in specific regions and observe how changes in this distribution occur throughout the development and correlate with the behavioral manipulations.
