### ISSUE TITLE
Limitations (Friday!)

### ISSUE THREAD

**Issue by venhoffl98** [Eugene3dotdev/CN-2023-pr-MDD-snRNA-seq#2]
What are the limitations mentioned in the paper (in the end)? Do they provide insight on how we could manage to avoid these?

**Comment by alex-prock** [comment]
The paper (Maitra et al., 2023, pp.11-12) notes the major limitation that cell type specific transcriptomes and the interaction between sex and MDD status could not be compared directly between males and females.
This is because the data comes from two different datasets, each containing only data of one sex. The datasets (may) differ in methodology (e.g. tissue collection approach or nuclei isolation protocol) and the paper's findings might be (partially) attributable to that.

However, the authors argue that a unified pre-processing pipeline (see #3) was applied on both data sets and that their findings are consistent with previous evidence related to sex-specific factors of depression.

Further limitations:
- DEGs at the cluster level for female samples not as robust (but supported by other findings)
- number of subjects small relative to number of genes tested
- findings not generalizable to all populations (subjects not diverse enough - all males caucasian, females: 4 hispanic, 2 african american, rest caucasian, 1 unknown)
- lack of cytoplasmic transcripts in snRNA-seq (snRNA-seq only reports nuclei) limits information about microglial states (some neurological disorders are associated with sub-populations of microglia) - but according to other research, nuclear microglia transcriptomes are a reliable proxy for cellular transcriptomes
- CellChat and STRING results about interaction of microglia with PV interneurons are speculative (conclusions about spatial and structural information is lost in snRNA-seq because it involves dissociation of the tissue)
- protein expression does not necessarily have to be changed by DEGs
- a few clusters may have low quality (these however did not contribute to the findings of differential expression much)
