### ISSUE TITLE
Preparation of data (Friday!)

### ISSUE THREAD

**Issue by venhoffl98** [Eugene3dotdev/CN-2023-pr-MDD-snRNA-seq#3]
How was the data prepared/cleaned in the paper? Which steps did they do before analyzing the data?

**Comment by Louises99** [comment]
### Sequencing, alignment, and generation of count matrices
o	Samples in f. cohort: Illumina NovaSeq 6000 (36 samples); BGI DNG-seq technology (2 samples)
o	Samples in m. cohort: realignment and count matrices generated with Cell Ranger version 5.0.1 against the GRCh38 reference
	‘cellranger count’ command using ‘-include-intronts’ option and all other options set to default
o	metadata: % of reads from mitochondrially encoded genes were calculated before filtering and used as a quality control parameter for nuclei filtering
	Outcome: 160,711 high-quality nuclei with comparable contributions of sex
	51% from females; 58% MDD disease status

### Dimensionality reduction and data integration
o	SCTransform on each Seurat object individually
o	SelectIntegrationFeatures function to set the variable genes for downstream analysis
	Downscaling cells and run log normalization
	Regress out NCount_RNA and percent.mt from counts
o	Harmony: to correct PCA components

### Clustering
o	Harmony: to correct for covariates incl. batch effects
o	Scclusteval workflow (FindClusters function): to test range of combinations of clustering parameters (Seurat package)
o	Jaccard indices: stability comparison workflow (with customization)
	Outcome: identification of 41 nuclei clusters

### Cluster annotation
o	Wilcoxauc function from presto with default parameters and filtered
o	Seurat AddMoleculeScore function to assess expression of cell type specific genes from BRETIGEA
	Outcome: out of the 41 clusters, 40 could each be confidently annotated to 1 of 7 major brain cell types

### Assessment of clustering quality
o	Comparing contributions of batches, groups, brain banks and subjects
	Outcome: singe cluster with mixes expression profile and 2 other clusters showed evidence of possible technical effects (ExN17 and ExN5) rather than biologically driven cell subtypes or cell states

### Comparing to other datasets
o	MetaNeighbor: match the gene expression patterns of the clusters to published clusters in several other human brain datasets
o	Seurat : downstream analysis and processing of filtered gene barcode matrices
	transfer labels for layer annotation from a spatial transcriptomics dataset
	SCTransform: to process Spatial and sNRA-seq
o	SelectIntegrationFeatures function
	Canonical correlation analysis” option: to identify transfer anchors
	Outcome: close correspondence was found between observed cell types
o	emphasizing that the quality of the data, clustering and annotation are at par with other recent snRNA-seq datasets for the human brain

### Pseudotime trajectory analysis
o	Slingshot: further characterize oligodendrocytes lineage (OL) clusters
o	tradeSeq: to split the date for males and females
o	plotSmoothers function; visualize the fitted expression of OL marker genes

### Cell type proportions comparison
o	rstaxix
	Wilcoxon test (R package boot): to mitigate outlier effects
	Random subsampling: to examine distribution of p-values
o	Kruskal-Wallis test: comparing sequencing quality control metrics
